### ISSUE TITLE
Add support for binary_sensor

### ISSUE THREAD

**Issue by ruimarinho** [elric91/homeassistant_zigate#15]
I think ideally the Xiaomi Door Sensor should behave as a `binary_sensor` instead of the suggested config as a `switch` as there is no action available - it would either report as open or closed.

**Comment by elric91** [comment]
Yes I'm thinking about it
You can already configure it as one, but you loose all the advantages related to the switch behavior and representation

**Comment by Neraud** [comment]
A binary_sensor can be typed to represent a door using a device_class : https://home-assistant.io/components/binary_sensor/

**Comment by ruimarinho** [comment]
I'm using this as an alternative:

```yaml
- platform: template
  sensors:
    main_door_binary_sensor:
      value_template: "{{ is_state('sensor.main_door', 'on-press') }}"
      device_class: door
      entity_id: sensor.main_door
```

I don't think it would work out of the box, would it?

```yaml
- platform: zigate
  sensors:
    main_door_binary_sensor:
      device_class: door
      entity_id: sensor.main_door
```

@elric91 - thanks for the great work on this component.
